name: Build and Upload tar.gz to Nexus

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Try auto fix vulnerabilities
        run: npm audit fix || true   # 자동으로 고칠 수 있는 것만 수
        
      - name: Update browserslist DB  # ← 이 줄 추가
        run: npx update-browserslist-db@latest
        
      - name: Build Vite
        run: npm run build
        
      - name: Check output folder  # 자동 감지!
        run: |
          if [ -d "dist" ]; then
            echo " Vite detected (dist/)"
            BUILD_DIR="dist"
          elif [ -d "build" ]; then  
            echo " CRA detected (build/)"
            BUILD_DIR="build"
          else
            echo " No output folder!"
            exit 1
          fi
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV



      - name: Run Trivy scanner      # 빌드 후 → Nexus 전
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'            # build/ + node_modules 검사
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'             # 취약점 있으면 중단!
      - name: Archive dist to tar.gz
        run: |
          mkdir -p artifacts
          tar -czf artifacts/build-${{ github.sha }}.tar.gz build # build/ 사용
          echo "✅ build folder archived"

      - name: Upload tar.gz to Nexus raw repo
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          FILE="artifacts/build-${{ github.sha }}.tar.gz"
          curl -v \
            -u "${NEXUS_USER}:${NEXUS_PASSWORD}" \
            --upload-file "${FILE}" \
            "http://10.0.0.152:8081/repository/second/yjTest/build-${{ github.sha }}.tar.gz"

            
